<a href="https://colab.research.google.com/github/antopeza/Final-Project-Brainster/blob/main/New_code_Doc2Vec.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
from numpy import random
from numpy import vstack
import matplotlib.pyplot as plt
import os 

import re

import string
from string import punctuation

from sklearn.model_selection import ShuffleSplit
from sklearn.ensemble import RandomForestClassifier
from sklearn.experimental import enable_halving_search_cv 
from sklearn.model_selection import HalvingGridSearchCV

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn import svm
from sklearn.svm import SVC
from sklearn.svm import LinearSVC
import sklearn.metrics as metrics
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

import xgboost as xgb

import nltk
from nltk.stem import WordNetLemmatizer, PorterStemmer, LancasterStemmer
from nltk.corpus import wordnet, stopwords
from nltk import pos_tag, word_tokenize

import gensim
from gensim.parsing.preprocessing import remove_stopwords

from keras.preprocessing.text import Tokenizer
from keras_preprocessing.sequence import pad_sequences
from keras.models import Model, Sequential, load_model
from keras.layers import Input, Embedding, LSTM, Dense
from keras.callbacks import ModelCheckpoint, EarlyStopping

from imblearn.over_sampling import SMOTE
from collections import Counter

#from scikeras.wrappers import KerasClassifier

import pickle
from pickle import dump
from pickle import load

from imblearn.over_sampling import SMOTE
from collections import Counter

%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [3]:
from google.colab import drive 
drive.mount('/drive')

Mounted at /drive


In [4]:
nltk.download("punkt")
nltk.download("stopwords")
nltk.download("wordnet")
nltk.download("averaged_perceptron_tagger")
nltk.download('omw-1.4')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...


True

In [5]:
stops = set(stopwords.words('english'))
#print(stops)

In [6]:
stemmer =  PorterStemmer()
lemmer = WordNetLemmatizer()

In [7]:
#df_raw = pd.read_csv(path)
df_raw = pd.read_csv('/drive/My Drive/MACHINE LEARNING/FINAL PROJECT/train.csv')

In [ ]:
print('shape of df  = ', df_raw.shape)
print()
df_raw.head(2)

shape of df  =  (404290, 6)



id  qid1  qid2                                          question1  \
0   0     1     2  What is the step by step guide to invest in sh...   
1   1     3     4  What is the story of Kohinoor (Koh-i-Noor) Dia...   

                                           question2  is_duplicate  
0  What is the step by step guide to invest in sh...             0  
1  What would happen if the Indian government sto...             0

In [ ]:
df_raw[df_raw.isnull().any(axis=1)]

id    qid1    qid2                         question1  \
105780  105780  174363  174364    How can I develop android app?   
201841  201841  303951  174364  How can I create an Android app?   
363362  363362  493340  493341                               NaN   

                                                question2  is_duplicate  
105780                                                NaN             0  
201841                                                NaN             0  
363362  My Chinese name is Haichao Yu. What English na...             0

In [8]:
df_raw = df_raw.fillna("")
df_raw.isnull().sum()

id              0
qid1            0
qid2            0
question1       0
question2       0
is_duplicate    0
dtype: int64

In [9]:
# randomly selected samples from df for the new df to perform operations
df = df_raw.sample(5000)
df = df[['question1', 'question2', 'is_duplicate']]
print(df.shape)

(5000, 3)


In [ ]:
df_copy = df.copy()

# Clean Data

In [10]:
def get_wordnet_pos(tag):
    if tag.startswith("N"):
        return wordnet.NOUN
    if tag.startswith("J"):
        return wordnet.ADJ
    if tag.startswith("V"):
        return wordnet.VERB
    if tag.startswith("R"):
        return wordnet.ADV
    return wordnet.NOUN

def clean_sentence(sentence, stopwords = False, lemmatize = False, stem = False):
    sentence = sentence.lower().strip()
    sentence = re.sub(r'[^a-z0-9\s]', '', sentence)  # removing all caracters that are not alpha numeric
    #sentence = re.sub(r'\s{2,}', ' ', sentence
   
    sentence = sentence.translate(str.maketrans('', '', string.punctuation))  # remove punctuation
    
    if stopwords:
        sentence = remove_stopwords(sentence)  
        
    if lemmatize:
        nltk_tagged = nltk.pos_tag(nltk.word_tokenize(sentence))
        wn_tagged = map(lambda x: (x[0], get_wordnet_pos(x[1])), nltk_tagged)
        res_words = []
        for word, tag in wn_tagged:
            if tag is None:
                res_words.append(word)
            else :
                res_words.append(lemmer.lemmatize(word, tag))
        sentence = " ".join(res_words)
        
    if stem:
        sent_stemmed = ''
        for word in sentence.split():
            sent_stemmed += ' '+ stemmer.stem(word)
        sentence = sent_stemmed
   
    return sentence

def get_cleaned_senteces(df, stopwords = False, lemmatize = False, stem = False):
    #sents1 = dfq[['question1']]  
    #sents2 = dfq[['question2']]
    cleaned_sentences1 = []
    cleaned_sentences2 = []
    
    for index, row in df.iterrows():
        # print (index, row)
        cleaned1 = clean_sentence(row['question1'], stopwords, lemmatize, stem) 
        cleaned2 = clean_sentence(row['question2'], stopwords, lemmatize, stem)

        cleaned_sentences1.append(cleaned1)
        cleaned_sentences2.append(cleaned2)
    return cleaned_sentences1, cleaned_sentences2

In [11]:
def to_df(q1cleaned, q2cleaned, df):
    '''cleaned sentences to df'''
    X_temp1 = pd.DataFrame()
    X_temp2 = pd.DataFrame()
    X_temp1['q1'] = pd.DataFrame(q1cleaned, index = df.index)
    X_temp2['q2'] = pd.DataFrame(q2cleaned, index = df.index)
    X_temp = pd.concat([X_temp1, X_temp2], axis = 1)
    X_temp['is_duplicate'] = df_raw['is_duplicate']
    return X_temp

#### With Stopwords, lemmatized

In [12]:
# With stopwords lemmatized, not stemmed
q1_sw_lemma, q2_sw_lemma = get_cleaned_senteces(df, stopwords = False, lemmatize = True, stem = False)
assert len(q1_sw_lemma) == len(q2_sw_lemma)
df_sw_lemma = to_df(q1_sw_lemma, q2_sw_lemma, df)
df_sw_lemma.shape

(5000, 3)

#### With Stopwords, stemmed

In [13]:
q1_sw_stem, q2_sw_stem = get_cleaned_senteces(df, stopwords = False, lemmatize = False, stem = True)
assert len(q1_sw_stem) == len(q2_sw_stem)
df_sw_stem = to_df(q1_sw_stem, q2_sw_stem, df)
df_sw_stem.shape

(5000, 3)

#### With stopwords, not lemmatized nor stemmed

In [14]:
q1_sw, q2_sw = get_cleaned_senteces(df, stopwords = False, lemmatize = False, stem = False)
assert len(q1_sw) == len(q2_sw)
df_sw = to_df(q1_sw, q2_sw, df)
df_sw.shape

(5000, 3)

#### Without Stopwords, lemmatized


In [15]:
q1_lemma, q2_lemma = get_cleaned_senteces(df, stopwords = True, lemmatize = True, stem = False)
assert len(q1_lemma) == len(q2_lemma)
df_lemma = to_df(q1_lemma, q2_lemma, df)
df_lemma.shape

(5000, 3)

#### Without Stopwords, stemmed

In [16]:
q1_stem, q2_stem = get_cleaned_senteces(df, stopwords = True, lemmatize = False, stem = True)
assert len(q1_stem) == len(q2_stem)
df_stem = to_df(q1_stem, q2_stem, df)
df_stem.shape

(5000, 3)

#### Without Stopwords, not lemmatized nor stemmed

In [17]:
q1_out, q2_out = get_cleaned_senteces(df, stopwords = True, lemmatize = False, stem = False)
assert len(q1_out) == len(q2_out)
df_out = to_df(q1_out, q2_out, df)
df_out.shape

(5000, 3)

In [ ]:
display ('With stopwords, without lemma and stem', df_sw.iloc[[22]])
display ('With stopwords, lemmatized and without stem', df_sw_lemma.iloc[[22]])
display ('With stopwords, stemmed and without lemma', df_sw_stem.iloc[[22]])
display ('Without stopwords, lemma and stem', df_out.iloc[[22]])
display ('Without stopwords and stem, lemmatized', df_lemma.iloc[[22]])
display ('Without stopwords and lemma, stemmed', df_stem.iloc[[22]])

'With stopwords, without lemma and stem'

q1  \
272872  what does it feel like to be on quora   

                                             q2  is_duplicate  
272872  what does it feel like to post on quora             1

'With stopwords, lemmatized and without stem'

q1  \
272872  what do it feel like to be on quora   

                                           q2  is_duplicate  
272872  what do it feel like to post on quora             1

'With stopwords, stemmed and without lemma'

q1  \
272872   what doe it feel like to be on quora   

                                             q2  is_duplicate  
272872   what doe it feel like to post on quora             1

'Without stopwords, lemma and stem'

q1                    q2  is_duplicate
272872  feel like quora  feel like post quora             1

'Without stopwords and stem, lemmatized'

q1                    q2  is_duplicate
272872  feel like quora  feel like post quora             1

'Without stopwords and lemma, stemmed'

q1                     q2  is_duplicate
272872   feel like quora   feel like post quora             1

In [ ]:
# print('Value counts:\n', X_sw_train['is_duplicate'].value_counts())
# print('\nPercent of labels value:\n', X_sw_train['is_duplicate'].value_counts()/X_sw_train['is_duplicate'].count()*100)
# X_sw_train['is_duplicate'].value_counts().plot(kind = 'bar')
# plt.title('\nDistribution of train labels', color = 'purple', size = 12)
# plt.show()

In [ ]:
# print('Value counts:\n', X_sw_test['is_duplicate'].value_counts())
# print('\nPercent of labels value:\n', X_sw_test['is_duplicate'].value_counts()/X_sw_test['is_duplicate'].count()*100)
# X_sw_test['is_duplicate'].value_counts().plot(kind = 'bar')
# plt.title('\nDistribution of test labels', color = 'purple', size = 12)
# plt.show()

In [ ]:
# display (X_sw_train.head(2))
# display(X_sw_test.head(2))
# display(df_clean.head(2))

In [ ]:
#X_sw_test[X_sw_test.isnull().any(axis=1)]

# *TOKENIZATION

In [14]:
def tokenization(text):
    tokens = re.split(' ',text)
    return tokens
def token(text):
    text = text.apply(lambda x: tokenization(x))
    return text

In [ ]:
#Tokenize - lemmatized data without stopwords
df_lemma['q1'] = df_lemma['q1'].pipe(token) 
df_lemma['q2'] = df_lemma['q2'].pipe(token) 
df_lemma.head(2)

q1                                q2  \
296968  [indian, lamborghini, usa, legally]  [study, usa, indian, good, idea]   
236824                     [learn, english]                  [learn, english]   

        is_duplicate  
296968             0  
236824             0

In [ ]:
# Tokenize - lemmatized data with stopwords
df_sw_lemma['q1'] = df_sw_lemma['q1'].pipe(token) 
df_sw_lemma['q2'] = df_sw_lemma['q2'].pipe(token) 
df_sw_lemma.head(2)

In [15]:
# Tokenize - Stemmed data with stopwords
df_sw_stem['q1'] = df_sw_stem['q1'].pipe(token) 
df_sw_stem['q2'] = df_sw_stem['q2'].pipe(token) 
df_sw_stem.head(2)

q1  \
11965   [, what, is, the, list, of, job, titl, at, rsm...   
342404  [, should, peopl, over, 94, not, be, allow, to...   

                                                       q2  is_duplicate  
11965   [, which, countri, is, the, best, to, work, in...             0  
342404  [, should, peopl, over, 97, not, be, allow, to...             1

In [ ]:
# Tokenize - Stemmed data without stopwords
df_stem['q1'] = df_stem['q1'].pipe(token) 
df_stem['q2'] = df_stem['q2'].pipe(token) 
df_stem.head(2)

q1  \
327246  [, can, i, regist, my, startup, compani, in, t...   
26328   [, what, is, a, good, entrylevel, job, in, the...   

                                                       q2  is_duplicate  
327246  [, can, i, start, a, compani, in, the, us, wit...             1  
26328   [, what, are, the, best, entri, level, job, in...             0

In [ ]:
# Tokenize - With stopwords, not lemmatized nor stemmed
df_sw['q1'] = df_sw['q1'].pipe(token) 
df_sw['q2'] = df_sw['q2'].pipe(token) 
df_stem.head(2)

In [ ]:
# Tokenize - Without stopwords, not lemmatized nor stemmed
df_out['q1'] = df_out['q1'].pipe(token) 
df_out['q2'] = df_out['q2'].pipe(token) 
df_out.head(2)

NameError: ignored

In [ ]:
df_sw_lemma.head(2)

q1  \
82361                            who invent wash machine   
12785  be hack a crime when someone do it to earn mon...   

                                                      q2  is_duplicate  
82361                     who invent the washing machine             1  
12785  what do pakistani girl look for in a guy objec...             0

#### Doc2Vec Without Stopwords, not stemmed not lemmatized

In [18]:
from gensim.models.doc2vec import Doc2Vec, TaggedDocument
def doc2vec(df):
  q1 = [TaggedDocument(d, [i]) for i, d in enumerate(df['q1'])]
  q2 = [TaggedDocument(d, [i]) for i, d in enumerate(df['q2'])]
  return q1, q2

In [19]:
def model_doc2vec(q1, vector, epochs):
  q1 = Doc2Vec(q1, dm = 1, vector_size = vector, window = 3, min_count = 2, epochs = epochs)
  return q1

### Run Doc2Vec Function

In [20]:
#lemmatized, without stopwords
q1_lemma_d2v, q2_lemma_d2v = doc2vec(df_lemma)
assert len(q1_lemma_d2v) == len(q2_lemma_d2v)

In [21]:
q1_lemma_d2v

[TaggedDocument(words='way hack facebook account', tags=[0]),
 TaggedDocument(words='vote donald trump president', tags=[1]),
 TaggedDocument(words='best way fight mental health issue', tags=[2]),
 TaggedDocument(words='cmu sphinx speech recognition', tags=[3]),
 TaggedDocument(words='know temperature sun', tags=[4]),
 TaggedDocument(words='slowly lose weight', tags=[5]),
 TaggedDocument(words='delete question quora', tags=[6]),
 TaggedDocument(words='data analyst job', tags=[7]),
 TaggedDocument(words='xiaomi redmi support video call', tags=[8]),
 TaggedDocument(words='step want start business', tags=[9]),
 TaggedDocument(words='mean dog bite dream', tags=[10]),
 TaggedDocument(words='log facebook password', tags=[11]),
 TaggedDocument(words='improve english aspect', tags=[12]),
 TaggedDocument(words='avoid mosquito house', tags=[13]),
 TaggedDocument(words='china best keep secret', tags=[14]),
 TaggedDocument(words='difference nagar palika nagar nigam nagar parishad', tags=[15]),
 Ta

In [71]:
#lemmatized with stopwords
q1_sw_lemma_d2v, q2_sw_lemma_d2v = doc2vec(df_sw_lemma)
assert len(q1_sw_lemma_d2v) == len(q2_sw_lemma_d2v)

In [18]:
#Stemmed without stopwords
q1_stem_d2v, q2_stem_d2v = doc2vec(df_stem)
assert len(q1_stem_d2v) == len(q2_stem_d2v)

In [19]:
#Stemmed with stopwords
q1_sw_stem_d2v, q2_sw_stem_d2v = doc2vec(df_sw_stem)
assert len(q1_sw_stem_d2v) == len(q2_sw_stem_d2v)

In [72]:
#With Stopwords, not lemmatized, not stemmed
q1_sw_d2v, q2_sw_d2v = doc2vec(df_sw)
assert len(q1_sw_d2v) == len(q2_sw_d2v)

In [73]:
#Without stopwords, not lemmatized, not stemmed 
q1_out_d2v, q2_out_d2v = doc2vec(df_out)
assert len(q1_out_d2v) == len(q2_out_d2v)

In [1]:
q1_out_d2v

NameError: ignored

### Activating Doc2Vec model

In [22]:
#PARAMETER FOR DOC2VEC MODEL 
vector = 100
epochs = 30

In [23]:
#lemmatized, without stopwords
X_q1_lemma_d2v = model_doc2vec(q1_lemma_d2v, vector, epochs)
X_q2_lemma_d2v = model_doc2vec(q2_lemma_d2v, vector, epochs)

In [25]:
X_q1_lemma_d2v[3]

array([-0.0412178 ,  0.0650392 , -0.03289882, -0.06239975, -0.04449236,
       -0.05524763,  0.01518274,  0.01704511, -0.00225002, -0.01494878,
       -0.02816903, -0.04239533, -0.01095802, -0.01047989,  0.04452044,
        0.01604926, -0.06396134,  0.03761509,  0.02213238, -0.02187038,
        0.07058885, -0.11782056,  0.02092711, -0.00885683, -0.00918218,
        0.00654902, -0.05415202, -0.03866808,  0.03968927, -0.03057757,
        0.06795979, -0.01312713,  0.04055554,  0.11056983,  0.04085131,
        0.00388256, -0.11027972, -0.00476998,  0.01890036, -0.03465449,
       -0.01525936, -0.02555254,  0.04056199, -0.00315608,  0.1644517 ,
       -0.02954346,  0.06438619, -0.09759032, -0.01544671,  0.02586464,
       -0.01098517,  0.04467121,  0.03315813, -0.01806021, -0.04481287,
       -0.04398055, -0.06040594, -0.02592981,  0.06214213,  0.0215547 ,
       -0.05317705,  0.02340506,  0.02212236,  0.03644421,  0.02416401,
        0.01749371,  0.05854058, -0.01435456,  0.03896435, -0.03

In [75]:
#lemmatized, with stopwords
X_q1_sw_lemma_d2v = model_doc2vec(q1_sw_lemma_d2v, vector, epochs)
X_q2_sw_lemma_d2v = model_doc2vec(q2_sw_lemma_d2v, vector, epochs)

In [76]:
#Stemmed, without stopwords
X_q1_stem_d2v = model_doc2vec(q1_stem_d2v, vector,  epochs)
X_q2_stem_d2v = model_doc2vec(q2_stem_d2v, vector,  epochs)

In [77]:
#Stemmed, with stopwords
X_q1_sw_stem_d2v = model_doc2vec(q1_sw_stem_d2v, vector, epochs)
X_q2_sw_stem_d2v = model_doc2vec(q2_sw_stem_d2v, vector, epochs)

In [78]:
#With Stopwords, not lemmatized, not stemmed
X_q1_sw_d2v = model_doc2vec(q1_sw_d2v, vector, epochs)
X_q2_sw_d2v = model_doc2vec(q2_sw_d2v, vector, epochs)

In [79]:
#Without stopwords, not lemmatized, not stemmed 
X_q1_out_d2v = model_doc2vec(q1_out_d2v, vector, epochs)
X_q2_out_d2v = model_doc2vec(q2_out_d2v, vector, epochs)


#### Convert to array 

In [80]:
# Lemmatized, without stopwords, not stemmed

size = len(df) - 1
arr_q1_lemma = X_q1_lemma_d2v[0] 

for i in range(size):
  arrT = X_q1_lemma_d2v[i+1]
  arr_q1_lemma = np.vstack([arr_q1_lemma, arrT])

arr_q2_lemma = X_q2_lemma_d2v[0] 

for i in range(size):
  arrT = X_q2_lemma_d2v[i+1]
  arr_q2_lemma = np.vstack([arr_q2_lemma, arrT])

assert arr_q1_lemma.shape == arr_q2_lemma.shape

#arr_q1_lemma = create_arrays(X_q1_lemma_d2v)
#arr_q2_lemma = create_arrays(X_q2_lemma_d2v)

In [81]:
# Lemmatized, with stopwords, not stemmed

size = len(df) - 1
arr_q1_sw_lemma = X_q1_sw_lemma_d2v[0] 

for i in range(size):
  arrT = X_q1_sw_lemma_d2v[i+1]
  arr_q1_sw_lemma = np.vstack([arr_q1_sw_lemma, arrT])

arr_q2_sw_lemma = X_q2_sw_lemma_d2v[0] 

for i in range(size):
  arrT = X_q2_sw_lemma_d2v[i+1]
  arr_q2_sw_lemma = np.vstack([arr_q2_sw_lemma, arrT])

assert arr_q1_sw_lemma.shape == arr_q2_sw_lemma.shape

# arr_q1_sw_lemma = create_arrays(X_q1_sw_lemma_d2v)
# arr_q2_sw_lemma = create_arrays(X_q2_sw_lemma_d2v) 

In [82]:
# Stemmed, with stopwords, not lemmatized

size = len(df) - 1
arr_q1_stem = X_q1_stem_d2v[0] 

for i in range(size):
  arrT = X_q1_stem_d2v[i+1]
  arr_q1_stem = np.vstack([arr_q1_stem, arrT])

arr_q2_stem = X_q2_stem_d2v[0] 

for i in range(size):
  arrT = X_q2_stem_d2v[i+1]
  arr_q2_stem = np.vstack([arr_q2_stem, arrT])

assert arr_q1_stem.shape == arr_q2_stem.shape

# arr_q1_stem = create_arrays(X_q1_stem_d2v)
# arr_q2_stem = create_arrays(X_q2_stem_d2v)

In [83]:
# Stemmed, without stopwords, not lemmatized 

size = len(df) - 1
arr_q1_sw_stem = X_q1_sw_stem_d2v[0] 

for i in range(size):
  arrT = X_q1_sw_stem_d2v[i+1]
  arr_q1_sw_stem = np.vstack([arr_q1_sw_stem, arrT])

arr_q2_sw_stem = X_q2_sw_stem_d2v[0] 

for i in range(size):
  arrT = X_q2_sw_stem_d2v[i+1]
  arr_q2_sw_stem = np.vstack([arr_q2_sw_stem, arrT])

assert arr_q1_sw_stem.shape == arr_q2_sw_stem.shape

# arr_q1_sw_stem = create_arrays(X_q1_sw_stem_d2v)
# arr_q2_sw_stem = create_arrays(X_q2_sw_stem_d2v)

In [84]:
# Without stopwords, not lemmatized, not stemmed
size = len(df) - 1
arr_q1_out = X_q1_out_d2v[0] 

for i in range(size):
  arrT = X_q1_out_d2v[i+1]
  arr_q1_out = np.vstack([arr_q1_out, arrT])

arr_q2_out = X_q2_out_d2v[0] 

for i in range(size):
  arrT = X_q2_out_d2v[i+1]
  arr_q2_out = np.vstack([arr_q2_out, arrT])

assert arr_q1_out.shape == arr_q2_out.shape

In [85]:
# With stopword, not lemmatized, not stemmed

size = len(df) - 1
arr_q1_sw = X_q1_sw_d2v[0] 

for i in range(size):
  arrT = X_q1_sw_d2v[i+1]
  arr_q1_sw = np.vstack([arr_q1_sw, arrT])

arr_q2_sw = X_q2_sw_d2v[0] 

for i in range(size):
  arrT = X_q2_sw_d2v[i+1]
  arr_q2_sw = np.vstack([arr_q2_sw, arrT])

assert arr_q1_sw.shape == arr_q2_sw.shape

### Convert to dataframe 

In [25]:
def df_arr(arr_q1, arr_q2, df):
  temp1 = pd.DataFrame(arr_q1)
  temp2 = pd.DataFrame(arr_q2)
  X_temp = pd.concat([temp1, temp2], axis=1)
  y = df['is_duplicate']
  y = np.array(y)
  y_df = pd.DataFrame(y)
  df_X = X_temp.join(y_df,  lsuffix='_left', rsuffix='_right')
  #X_temp['is_duplicate'] = df['is_duplicate']
  return df_X

In [86]:
# Dataframe - Lemmatized without stopwords 
lemma_df = df_arr(arr_q1_lemma, arr_q2_lemma, df)

In [87]:
# Dataframe - Lemmatized with stopwords 
sw_lemma_df = df_arr(arr_q1_sw_lemma, arr_q2_sw_lemma, df)

In [26]:
# Dataframe - Stemmed without stopwords 
stem_df = df_arr(arr_q1_stem, arr_q2_stem, df)

In [27]:
# Dataframe - Lemmatized with stopwords 
sw_stem_df = df_arr(arr_q1_sw_stem, arr_q2_sw_stem, df)

In [88]:
# Dataframe - With stopwords, not lemmatized, not stemmed
sw_df = df_arr(arr_q1_sw, arr_q2_sw, df)

In [89]:
# Dataframe - Without stopwords, not lemmatized, not stemmed
out_df = df_arr(arr_q1_out, arr_q2_out, df)

In [28]:
stem_df.head(2)


0_left         1         2         3         4         5         6  \
0 -0.007656 -0.017189 -0.058634  0.072262 -0.014387  0.013050 -0.043178   
1 -0.031230  0.023416  0.008874  0.074721 -0.016633 -0.025616 -0.050669   

          7         8         9  ...        91        92        93        94  \
0 -0.065979  0.055877 -0.036416  ... -0.054352  0.042411 -0.017314 -0.025635   
1 -0.018542  0.036259 -0.002108  ... -0.076787  0.021046 -0.026546  0.046404   

         95        96        97        98        99  0_right  
0  0.013351 -0.065088  0.013830  0.062138  0.054103        0  
1 -0.064159  0.009849  0.009103  0.022082  0.063962        1  

[2 rows x 201 columns]

In [29]:
df_stem.head(2)

q1                         q2  \
11965    list job titl rsm audit firm kuwait   countri best work kuwait   
342404                   peopl 94 allow vote        peopl 97 allow vote   

        is_duplicate  
11965              0  
342404             1

In [30]:
df_sw_stem.head(2)

q1  \
11965   [, what, is, the, list, of, job, titl, at, rsm...   
342404  [, should, peopl, over, 94, not, be, allow, to...   

                                                       q2  is_duplicate  
11965   [, which, countri, is, the, best, to, work, in...             0  
342404  [, should, peopl, over, 97, not, be, allow, to...             1

### Split Data

In [90]:
# Lemmatized with stopwords 
y_sw_lemma= sw_lemma_df['0_right']
X_train_sw_lemma, X_test_sw_lemma, y_train_sw_lemma, y_test_sw_lemma = train_test_split(sw_lemma_df, y_sw_lemma, stratify = y_sw_lemma, test_size = 0.15, random_state = 0)

In [91]:
# Lemmatized without stopwords 
y_lemma= lemma_df['0_right']
X_train_lemma, X_test_lemma, y_train_lemma, y_test_lemma = train_test_split(lemma_df, y_lemma, stratify = y_lemma, test_size = 0.15, random_state = 0)

In [44]:
# Stemmed with stopwords 
y_sw_stem= sw_stem_df['0_right']
X_train_sw_stem, X_test_sw_stem, y_train_sw_stem, y_test_sw_stem = train_test_split(sw_stem_df, y_sw_stem, stratify = y_sw_stem, test_size = 0.15, random_state = 0)

In [92]:
# Stemmed without stopwords 
y_stem= stem_df['0_right']
X_train_stem, X_test_stem, y_train_stem, y_test_stem = train_test_split(stem_df, y_stem, stratify = y_stem, test_size = 0.15, random_state = 0)

In [93]:
# With Stopwords, not lemmatized, not stemmed 
y_sw= sw_df['0_right']
X_train_sw, X_test_sw, y_train_sw, y_test_sw = train_test_split(sw_df, y_sw, stratify = y_sw, test_size = 0.15, random_state = 0)

In [94]:
# Without Stopwords, not lemmatized, not stemmed 
y_out= out_df['0_right']
X_train_out, X_test_out, y_train_out, y_test_out = train_test_split(out_df, y_out, stratify = y_out, test_size = 0.15, random_state = 0)

# MODELS

### Random Forest

In [33]:
def rf_clf(X_train, X_test, y_train, y_test):
    '''Parameter tuning for Random Forest Classifier and model fit'''
    
    splits = ShuffleSplit(n_splits = 1, test_size = .2, random_state = 0)
    rf_param_grid = {'n_estimators':[20, 50, 80], 'min_samples_split':[3, 13], 'max_depth': [10, 30, None]}
    rf_clf = RandomForestClassifier(random_state = 0)
    
    rf_search = HalvingGridSearchCV(rf_clf, rf_param_grid, cv = splits, factor = 2, scoring = 'accuracy', 
                                        max_resources = 5, aggressive_elimination = False, verbose = 0)
    rf_search.fit(X_train, y_train)
    
    rf_model = rf_search.best_estimator_
    
    y_pred = rf_model.predict(X_test)
    
    log_loss = metrics.log_loss(y_test, y_pred)
    accuracy = metrics.accuracy_score(y_test, y_pred)
    precision = metrics.precision_score(y_test, y_pred)
    recall = metrics.recall_score(y_test, y_pred)
    f1_score = metrics.f1_score(y_test, y_pred)
    print (rf_model)
    return accuracy, precision, recall, f1_score, log_loss, y_pred, rf_model

## Logistic Regression

In [34]:
def lr_clf(X_train, X_test, y_train, y_test):
    '''Parameter tuning for Logistic Regression Classifier and model fit'''
    
    splits = ShuffleSplit(n_splits = 1, test_size = .2, random_state = 0)
    lr_param_grid = {'C':[100, 10, 1.0, 0.1, 0.01], 'solver':['sag', 'lbfgs']}
    lr_clf = LogisticRegression(penalty = 'l2', random_state = 0)
   
    lr_d2v_search = HalvingGridSearchCV(lr_clf, lr_param_grid, cv = splits, factor = 2, scoring = 'accuracy', verbose = 0)
    lr_d2v_search.fit(X_train, y_train)
    
    lr_d2v_model = lr_d2v_search.best_estimator_
    y_pred_lr_d2v = lr_d2v_model.predict(X_test)
    lr_loss_d2v = metrics.log_loss(y_test, y_pred_lr_d2v)
    lr_acc_d2v = metrics.accuracy_score(y_test, y_pred_lr_d2v)
    print (lr_d2v_model)
    print('log loss', lr_loss_d2v, '\nacc', lr_acc_d2v)
    return lr_acc_d2v, lr_loss_d2v, y_pred_lr_d2v   

# Support Vector Classification - SVC

In [63]:
from sklearn.svm import SVC
def svc_clf(X_train, X_test, y_train, y_test):
  clf_svc = svm.SVC(kernel='sigmoid', decision_function_shape='ovr', random_state=None)   #kernel default='rbf', decision_function_shape='ovr', random_state=None


  clf_svc.fit(X_train, y_train)

  y_pred = clf_svc.predict(X_test)
  log_loss = metrics.log_loss(y_test, y_pred)
  accuracy = metrics.accuracy_score(y_test, y_pred)
  precision = metrics.precision_score(y_test, y_pred)
  recall = metrics.recall_score(y_test, y_pred)
  f1_score = metrics.f1_score(y_test, y_pred)
  return accuracy, precision, recall, f1_score, log_loss, y_pred

# Activate model functions

#### On Lemmatized data

In [95]:
# Lemmatized, without stopwords

#Random Forest
acc_rf_lemma, precision_rf_lemma, recall_rf_lemma, f1_score_rf_lemma, log_loss_rf_lemma, y_pred_rf_lemma, berf_lemma  = rf_clf(X_train_lemma, X_test_lemma, y_train_lemma, y_test_lemma)

report_rf_lemma = classification_report(y_pred_rf_lemma, y_test_lemma)
matrix_rf_lemma = confusion_matrix(y_pred_rf_lemma, y_test_lemma)
print('Classification Report - RF\n', report_rf_lemma)
print()
print('Confusion Matrix - RF\n', matrix_rf_lemma)

#Logistic Regression
lr_acc_lemma, lr_loss_lemma, y_pred_lr_lemma = lr_clf(X_train_lemma, X_test_lemma, y_train_lemma, y_test_lemma)
print()

# SVC 
acc_svc_lemma, precision_svc_lemma, recall_svc_lemma, f1_score_svc_lemma, log_loss_svc_lemma, y_pred_svc_lemma = svc_clf(X_train_lemma, X_test_lemma, y_train_lemma, y_test_lemma)

report_svc_lemma = classification_report(y_pred_svc_lemma, y_test_lemma)
matrix_svc_lemma = confusion_matrix(y_pred_svc_lemma, y_test_lemma)

print('Classification Report - SVC\n', report_svc_lemma)
print()
print('Confusion Matrix - SVC\n', matrix_svc_lemma)

RandomForestClassifier(max_depth=10, min_samples_split=3, n_estimators=20,
                       random_state=0)
Classification Report - RF
               precision    recall  f1-score   support

           0       1.00      0.96      0.98       492
           1       0.92      1.00      0.96       258

    accuracy                           0.97       750
   macro avg       0.96      0.98      0.97       750
weighted avg       0.97      0.97      0.97       750


Confusion Matrix - RF
 [[470  22]
 [  1 257]]
LogisticRegression(C=0.01, random_state=0, solver='sag')
log loss 9.992007221626413e-16 
acc 1.0

Classification Report - SVC
               precision    recall  f1-score   support

           0       0.99      0.99      0.99       475
           1       0.97      0.99      0.98       275

    accuracy                           0.99       750
   macro avg       0.98      0.99      0.99       750
weighted avg       0.99      0.99      0.99       750


Confusion Matrix - SVC
 [[468

In [96]:
# Lemmatized, with stopwords

#Random Forest
acc_rf_sw_lemma, precision_rf_sw_lemma, recall_rf_sw_lemma, f1_score_rf_sw_lemma, log_loss_rf_sw_lemma, y_pred_rf_sw_lemma, berf_sw_lemma  = rf_clf(X_train_sw_lemma, X_test_sw_lemma, y_train_sw_lemma, y_test_sw_lemma)

report_rf_sw_lemma = classification_report(y_pred_rf_sw_lemma, y_test_sw_lemma)
matrix_rf_sw_lemma = confusion_matrix(y_pred_rf_sw_lemma, y_test_sw_lemma)
print('Classification Report - RF\n', report_rf_sw_lemma)
print()
print('Confusion Matrix - RF\n', matrix_rf_sw_lemma)
print()

#Logistic Regression
lr_acc_sw_lemma, lr_loss_sw_lemma, y_pred_lr_sw_lemma = lr_clf(X_train_sw_lemma, X_test_sw_lemma, y_train_sw_lemma, y_test_sw_lemma)
print()

# SVC 
acc_svc_sw_lemma, precision_svc_sw_lemma, recall_svc_sw_lemma, f1_score_svc_sw_lemma, log_loss_svc_sw_lemma, y_pred_svc_sw_lemma = svc_clf(X_train_sw_lemma, X_test_sw_lemma, y_train_sw_lemma, y_test_sw_lemma)

report_svc_sw_lemma = classification_report(y_pred_svc_sw_lemma, y_test_sw_lemma)
matrix_svc_sw_lemma = confusion_matrix(y_pred_svc_sw_lemma, y_test_sw_lemma)

print('Classification Report - SVC\n', report_svc_sw_lemma)
print()
print('Confusion Matrix - SVC\n', matrix_svc_sw_lemma)

RandomForestClassifier(max_depth=10, min_samples_split=3, n_estimators=20,
                       random_state=0)
Classification Report - RF
               precision    recall  f1-score   support

           0       1.00      0.97      0.98       486
           1       0.95      1.00      0.97       264

    accuracy                           0.98       750
   macro avg       0.97      0.98      0.98       750
weighted avg       0.98      0.98      0.98       750


Confusion Matrix - RF
 [[471  15]
 [  0 264]]

LogisticRegression(C=0.1, random_state=0, solver='sag')
log loss 9.992007221626413e-16 
acc 1.0

Classification Report - SVC
               precision    recall  f1-score   support

           0       1.00      0.99      1.00       475
           1       0.99      1.00      0.99       275

    accuracy                           0.99       750
   macro avg       0.99      1.00      0.99       750
weighted avg       0.99      0.99      0.99       750


Confusion Matrix - SVC
 [[471

# With stopwords, not lemmatized nor stemmed

In [97]:
# With stopwords, not lemmatized, nor stemmed

#Random Forest
acc_rf_sw, precision_rf_sw, recall_rf_sw, f1_score_rf_sw, log_loss_rf_sw, y_pred_rf_sw, berf_sw  = rf_clf(X_train_sw, X_test_sw, y_train_sw, y_test_sw)

report_rf_sw = classification_report(y_pred_rf_sw, y_test_sw)
matrix_rf_sw = confusion_matrix(y_pred_rf_sw, y_test_sw)
print('Classification Report - RF\n', report_rf_sw)
print()
print('Confusion Matrix - RF\n', matrix_rf_sw)
print()

#Logistic Regression
lr_acc_sw, lr_loss_sw, y_pred_lr_sw = lr_clf(X_train_sw, X_test_sw, y_train_sw, y_test_sw)
print()

# SVC 
acc_svc_sw, precision_svc_sw, recall_svc_sw, f1_score_svc_sw, log_loss_svc_sw, y_pred_svc_sw = svc_clf(X_train_sw, X_test_sw, y_train_sw, y_test_sw)

report_svc_sw = classification_report(y_pred_svc_sw, y_test_sw)
matrix_svc_sw = confusion_matrix(y_pred_svc_sw, y_test_sw)

print('Classification Report - SVC\n', report_svc_sw)
print()
print('Confusion Matrix - SVC\n', matrix_svc_sw)

RandomForestClassifier(max_depth=10, min_samples_split=3, n_estimators=20,
                       random_state=0)
Classification Report - RF
               precision    recall  f1-score   support

           0       1.00      0.96      0.98       493
           1       0.92      1.00      0.96       257

    accuracy                           0.97       750
   macro avg       0.96      0.98      0.97       750
weighted avg       0.97      0.97      0.97       750


Confusion Matrix - RF
 [[471  22]
 [  0 257]]

LogisticRegression(C=0.1, random_state=0, solver='sag')
log loss 9.992007221626413e-16 
acc 1.0

Classification Report - SVC
               precision    recall  f1-score   support

           0       1.00      0.99      1.00       475
           1       0.99      1.00      0.99       275

    accuracy                           0.99       750
   macro avg       0.99      1.00      0.99       750
weighted avg       0.99      0.99      0.99       750


Confusion Matrix - SVC
 [[471

### Without stopwords, not lemmatized nor stemmed

In [98]:
# Without stopwords, not lemmatized, nor stemmed

#Random Forest
acc_rf_out, precision_rf_out, recall_rf_out, f1_score_rf_out, log_loss_rf_out, y_pred_rf_out, berf_out  = rf_clf(X_train_out, X_test_out, y_train_out, y_test_out)

report_rf_out = classification_report(y_pred_rf_out, y_test_out)
matrix_rf_out = confusion_matrix(y_pred_rf_out, y_test_out)
print('Classification Report - RF\n', report_rf_out)
print()
print('Confusion Matrix - RF\n', matrix_rf_out)
print()

#Logistic Regression
lr_acc_out, lr_loss_out, y_pred_lr_out = lr_clf(X_train_out, X_test_out, y_train_out, y_test_out)
print()

# SVC 
acc_svc_out, precision_svc_out, recall_svc_out, f1_score_svc_out, log_loss_svc_out, y_pred_svc_out = svc_clf(X_train_out, X_test_out, y_train_out, y_test_out)

report_svc_out = classification_report(y_pred_svc_out, y_test_out)
matrix_svc_out = confusion_matrix(y_pred_svc_out, y_test_out)

print('Classification Report - SVC\n', report_svc_out)
print()
print('Confusion Matrix - SVC\n', matrix_svc_out)

RandomForestClassifier(max_depth=10, min_samples_split=3, n_estimators=20,
                       random_state=0)
Classification Report - RF
               precision    recall  f1-score   support

           0       1.00      0.99      0.99       477
           1       0.98      1.00      0.99       273

    accuracy                           0.99       750
   macro avg       0.99      0.99      0.99       750
weighted avg       0.99      0.99      0.99       750


Confusion Matrix - RF
 [[471   6]
 [  0 273]]

LogisticRegression(C=0.01, random_state=0, solver='sag')
log loss 9.992007221626413e-16 
acc 1.0

Classification Report - SVC
               precision    recall  f1-score   support

           0       1.00      0.99      0.99       475
           1       0.98      0.99      0.99       275

    accuracy                           0.99       750
   macro avg       0.99      0.99      0.99       750
weighted avg       0.99      0.99      0.99       750


Confusion Matrix - SVC
 [[46

# Stemmed data with stopwords

In [99]:
# Stemmed with stopwords

#Random Forest
acc_rf_sw_stem, precision_rf_sw_stem, recall_rf_sw_stem, f1_score_rf_sw_stem, log_loss_rf_sw_stem, y_pred_rf_sw_stem, berf_sw_stem  = rf_clf(X_train_sw_stem, X_test_sw_stem, y_train_sw_stem, y_test_sw_stem)

report_rf_sw_stem = classification_report(y_pred_rf_sw_stem, y_test_sw_stem)
matrix_rf_sw_stem = confusion_matrix(y_pred_rf_sw_stem, y_test_sw_stem)
print('Classification Report - RF\n', report_rf_sw_stem)
print()
print('Confusion Matrix - RF\n', matrix_rf_sw_stem)
print()

#Logistic Regression
lr_acc_sw_stem, lr_loss_sw_stem, y_pred_lr_sw_stem = lr_clf(X_train_sw_stem, X_test_sw_stem, y_train_sw_stem, y_test_sw_stem)
print()

# SVC 
acc_svc_sw_stem, precision_svc_sw_stem, recall_svc_sw_stem, f1_score_svc_sw_stem, log_loss_svc_sw_stem, y_pred_svc_sw_stem = svc_clf(X_train_sw_stem, X_test_sw_stem, y_train_sw_stem, y_test_sw_stem)

report_svc_sw_stem = classification_report(y_pred_svc_sw_stem, y_test_sw_stem)
matrix_svc_sw_stem = confusion_matrix(y_pred_svc_sw_stem, y_test_sw_stem)

print('Classification Report - SVC\n', report_svc_sw_stem)
print()
print('Confusion Matrix - SVC\n', matrix_svc_sw_stem)

RandomForestClassifier(max_depth=10, min_samples_split=3, n_estimators=20,
                       random_state=0)
Classification Report - RF
               precision    recall  f1-score   support

           0       1.00      0.95      0.97       494
           1       0.91      1.00      0.95       256

    accuracy                           0.97       750
   macro avg       0.96      0.97      0.96       750
weighted avg       0.97      0.97      0.97       750


Confusion Matrix - RF
 [[470  24]
 [  1 255]]

LogisticRegression(C=0.01, random_state=0, solver='sag')
log loss 9.992007221626413e-16 
acc 1.0

Classification Report - SVC
               precision    recall  f1-score   support

           0       0.99      0.99      0.99       469
           1       0.98      0.98      0.98       281

    accuracy                           0.98       750
   macro avg       0.98      0.98      0.98       750
weighted avg       0.98      0.98      0.98       750


Confusion Matrix - SVC
 [[46

# Stemmed without stopwords


In [100]:
# Stemmed with stopwords

#Random Forest
acc_rf_stem, precision_rf_stem, recall_rf_stem, f1_score_rf_stem, log_loss_rf_stem, y_pred_rf_stem, berf_stem  = rf_clf(X_train_stem, X_test_stem, y_train_stem, y_test_stem)

report_rf_stem = classification_report(y_pred_rf_stem, y_test_stem)
matrix_rf_stem = confusion_matrix(y_pred_rf_stem, y_test_stem)
print('Classification Report - RF\n', report_rf_stem)
print()
print('Confusion Matrix - RF\n', matrix_rf_stem)
print()

#Logistic Regression
lr_acc_stem, lr_loss_stem, y_pred_lr_stem = lr_clf(X_train_stem, X_test_stem, y_train_stem, y_test_stem)
print()

# SVC 
acc_svc_stem, precision_svc_stem, recall_svc_stem, f1_score_svc_stem, log_loss_svc_stem, y_pred_svc_stem = svc_clf(X_train_stem, X_test_stem, y_train_stem, y_test_stem)

report_svc_stem = classification_report(y_pred_svc_stem, y_test_stem)
matrix_svc_stem = confusion_matrix(y_pred_svc_stem, y_test_stem)

print('Classification Report - SVC\n', report_svc_stem)
print()
print('Confusion Matrix - SVC\n', matrix_svc_stem)

RandomForestClassifier(max_depth=10, min_samples_split=3, n_estimators=20,
                       random_state=0)
Classification Report - RF
               precision    recall  f1-score   support

           0       1.00      0.98      0.99       482
           1       0.96      1.00      0.98       268

    accuracy                           0.99       750
   macro avg       0.98      0.99      0.98       750
weighted avg       0.99      0.99      0.99       750


Confusion Matrix - RF
 [[471  11]
 [  0 268]]

LogisticRegression(C=0.1, random_state=0, solver='sag')
log loss 9.992007221626413e-16 
acc 1.0

Classification Report - SVC
               precision    recall  f1-score   support

           0       1.00      0.99      0.99       477
           1       0.98      1.00      0.99       273

    accuracy                           0.99       750
   macro avg       0.99      0.99      0.99       750
weighted avg       0.99      0.99      0.99       750


Confusion Matrix - SVC
 [[471

In [114]:
result_df = pd.DataFrame(index = ['accuracy', 'loss'])

In [132]:
#DATAFRAME RESULT FOR STEMMED DATA WITHOUT STOPWORDS
result_df['random_forest_d2v_stemmed'] = f1_score_rf_stem, log_loss_rf_stem
result_df['log_regression_d2v_stemmed'] = lr_acc_stem, lr_loss_stem
result_df['svc_d2v_stem'] = f1_score_svc_stem, log_loss_svc_stem

result_df.drop(['rf_d2v_sw_stem', 'lr_d2v_sw_stem', 'svc_d2v_sw_stem'], axis=1)

In [133]:
result_df

rf_d2v_sw_stem  lr_d2v_sw_stem  svc_d2v_sw_stem  \
accuracy        0.985333    1.000000e+00          0.99200   
loss            0.506569    9.992007e-16          0.27631   

          random_forest_d2v_stemmed  log_regression_d2v_stemmed  svc_d2v_stem  
accuracy                   0.979890                1.000000e+00       0.98913  
loss                       0.506569                9.992007e-16       0.27631

# Cosine Similarity

In [101]:
from sklearn.metrics.pairwise import cosine_similarity

In [104]:
#cosine = cosine_similarity(X_train_lemma, y_train_lemma, dense_output=True)

In [113]:
cosine_similarity(arr_q1_lemma , arr_q2_lemma, dense_output=True)

array([[0.77353704, 0.6493094 , 0.7844405 , ..., 0.61083734, 0.6324987 ,
        0.8206404 ],
       [0.33382827, 0.8227184 , 0.5351572 , ..., 0.5696451 , 0.4045978 ,
        0.5432366 ],
       [0.57329106, 0.65007234, 0.86115694, ..., 0.77194357, 0.52491057,
        0.7496874 ],
       ...,
       [0.5479884 , 0.5654626 , 0.74211514, ..., 0.8167627 , 0.58999306,
        0.8312438 ],
       [0.63509995, 0.54801077, 0.78231716, ..., 0.63727254, 0.88014674,
        0.81301326],
       [0.6825827 , 0.6387254 , 0.84284997, ..., 0.6468858 , 0.6542733 ,
        0.8440794 ]], dtype=float32)

In [111]:
cosine_similarity(arr_q1_lemma , arr_q2_lemma)
cosine_similarity(arr_q1_sw_lemma , arr_q2_sw_lemma)
cosine_similarity(arr_q1_stem , arr_q2_stem)
cosine_similarity(arr_q1_sw_stem , arr_q2_sw_stem)
cosine_similarity(arr_q1_sw , arr_q2_sw)
cosine_similarity(arr_q1_out , arr_q2_out)

# Doc2Vec and similarity

In [ ]:
model_doc2vec = Doc2Vec(vector_size =20, window=2, min_count=1, epochs=50)

In [ ]:
model_doc2vec.build_vocab(X_train_tagged)

In [ ]:
model_doc2vec.train(X_train_tagged, total_examples=model_doc2vec.corpus_count, epochs=model_doc2vec.epochs)

In [ ]:
print(model_doc2vec.infer_vector(X_sw_test))

[ 0.00553507 -0.02057612 -0.00601494  0.01590716  0.00477619 -0.00957217
 -0.01354616  0.01898067 -0.00717559  0.00853975  0.00150559 -0.01450056
 -0.00628278 -0.02179538 -0.01993607 -0.02084691  0.00312932 -0.0190215
 -0.00581192  0.01894295]


In [ ]:
#TEST THE MODEL ON X_sw_test

test = model_doc2vec.infer_vector(X_sw_test)
model_doc2vec.docvecs.most_similar(positive = [test])
#positive = List of sentences that contribute positively.


[(1607, 0.3674626350402832),
 (1454, 0.3508557975292206),
 (1876, 0.3459669351577759),
 (2316, 0.3180397152900696),
 (1868, 0.31006860733032227),
 (389, 0.3054264485836029),
 (1438, 0.28425800800323486),
 (1760, 0.272051066160202),
 (2109, 0.2675776481628418),
 (2054, 0.2670101821422577)]

# buen codigo para doc2vec cosine similarity

In [ ]:
# import
from gensim.models.doc2vec import Doc2Vec, TaggedDocument
q1_tag = [TaggedDocument(d, [i]) for i, d in enumerate(df_clean['q1'])]
q2_tag = [TaggedDocument(d, [i]) for i, d in enumerate(df_clean['q2'])]
#tagged_data

In [ ]:
q1_model = Doc2Vec(q1_tag, vector_size = 20, window = 2, min_count = 1, epochs = 100)
q2_model = Doc2Vec(q2_tag, vector_size = 20, window = 2, min_count = 1, epochs = 100)

In [ ]:
q1_model[0]

array([ 0.5810266 ,  1.2083697 ,  0.9162264 , -0.0174998 , -0.15741944,
       -1.4726185 , -0.62223524,  0.5812599 ,  0.7438206 , -0.04712546,
       -0.8470433 ,  0.6188074 ,  0.6834843 ,  0.34443977, -0.66070366,
        0.66500264,  0.1121475 , -0.8982408 ,  0.18651539, -0.18247873],
      dtype=float32)

In [ ]:
# #cosine similarity - to finish 
# test_doc = word_tokenize("What is the step by step guide to invest".lower())
# test_doc_vector = model.infer_vector(test_doc)
# model.docvecs.most_similar(positive = [test_doc_vector])


[(1555, 0.7962811589241028),
 (2760, 0.7377956509590149),
 (1810, 0.7373658418655396),
 (2765, 0.7061798572540283),
 (2729, 0.6963450312614441),
 (1806, 0.688534677028656),
 (1839, 0.685553789138794),
 (2233, 0.6750451326370239),
 (1854, 0.6687722206115723),
 (2190, 0.6662200093269348)]

buen codigo

In [ ]:
# test_doc = word_tokenize("What is the step by step guide to invest".lower())
# test_doc_vector = model.infer_vector(test_doc)
# model.docvecs.most_similar(positive = [test_doc_vector])

[(1854, 0.8070089221000671),
 (42, 0.7843912839889526),
 (958, 0.779266357421875),
 (1183, 0.7622733116149902),
 (1839, 0.7594348192214966),
 (2007, 0.7579702138900757),
 (2760, 0.7547283172607422),
 (909, 0.7446797490119934),
 (2765, 0.7345895767211914),
 (1835, 0.732286810874939)]